ARM:PXA95X: fix daily build 'mci0_platform_data' load error
saarbmg1-ics daily build(2012-06-12) has a load error.

Error log:
arm-eabi-ld: arch/arm/mach-pxa/built-in.o: in function
mmc_jira_2339_wr_before_lpm:ramdump.c(.text+0xc1e8):
error: undefined reference to 'mci0_platform_data'

This caused by patch 012f283916f8d520cf78318cbd73e91230bab84b.
In that patch, mci0_platform_data has exported in saarc.c for
nevo jira-2339 workaround.
So in saarbmg1 project, don't need to build the  workaround
with mci0_platform_data.
Add this patch to fix load error.

Change-Id: I2de676ee733a00e1b2fc82ed43a2349bc8a80145
Signed-off-by: Tim Wang <wangtt@marvell.com>